// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQYo-pg9ND_Sfu1KZ2tW5bG6A7z2Se8o',
    appId: '1:1057276878548:web:d92cc2567e8198e53b2541',
    messagingSenderId: '1057276878548',
    projectId: 'shoopy-9f38f',
    authDomain: 'shoopy-9f38f.firebaseapp.com',
    storageBucket: 'shoopy-9f38f.firebasestorage.app',
    measurementId: 'G-NQ673N5TKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFh7eZYrZ-7EM1bidZrLfmRqyAOYdvdCU',
    appId: '1:1057276878548:android:400f3f20e8e85b193b2541',
    messagingSenderId: '1057276878548',
    projectId: 'shoopy-9f38f',
    storageBucket: 'shoopy-9f38f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9afQSQ1pvXFEmGmUftqsPEfFjagmaAkw',
    appId: '1:1057276878548:ios:ac9749e8903c2df03b2541',
    messagingSenderId: '1057276878548',
    projectId: 'shoopy-9f38f',
    storageBucket: 'shoopy-9f38f.firebasestorage.app',
    iosBundleId: 'com.example.shoopy',
  );
}
